-- Import inicial --

-- Valores de la tabla paises --
INSERT INTO countries (pais_Id, countriename)  VALUES
('US', 'United States'),
('CA', 'Canada'),
('AF', 'Afghanistan'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AS', 'American Samoa'),
('AD', 'Andorra'),
('AO', 'Angola'),
( 'AI', 'Anguilla'),
( 'AQ', 'Antarctica'),
( 'AG', 'Antigua and/or Barbuda'),
( 'AR', 'Argentina'),
( 'AM', 'Armenia'),
( 'AW', 'Aruba'),
( 'AU', 'Australia'),
( 'AT', 'Austria'),
( 'AX', 'Åland Islands'),
( 'AZ', 'Azerbaijan'),
( 'BS', 'Bahamas'),
( 'BH', 'Bahrain'),
('BD', 'Bangladesh'),
( 'BB', 'Barbados'),
( 'BY', 'Belarus'),
( 'BE', 'Belgium'),
( 'BZ', 'Belize'),
( 'BJ', 'Benin'),
( 'BM', 'Bermuda'),
( 'BT', 'Bhutan'),
( 'BO', 'Bolivia'),
( 'BA', 'Bosnia and Herzegovina'),
( 'BW', 'Botswana'),
( 'BV', 'Bouvet Island'),
( 'BR', 'Brazil'),
( 'IO', 'British lndian Ocean Territory'),
( 'BN', 'Brunei Darussalam'),
( 'BG', 'Bulgaria'),
( 'BF', 'Burkina Faso'),
( 'BI', 'Burundi'),
( 'KH', 'Cambodia'),
( 'CM', 'Cameroon'),
( 'CV', 'Cape Verde'),
( 'KY', 'Cayman Islands'),
( 'CF', 'Central African Republic'),
( 'TD', 'Chad'),
( 'CL', 'Chile'),
( 'CN', 'China'),
( 'CX', 'Christmas Island'),
( 'CC', 'Cocos (Keeling) Islands'),
( 'CO', 'Colombia'),
( 'KM', 'Comoros'),
( 'CG', 'Congo'),
( 'CK', 'Cook Islands'),
( 'CR', 'Costa Rica'),
( 'HR', 'Croatia (Hrvatska)'),
( 'CU', 'Cuba'),
( 'CY', 'Cyprus'),
( 'CZ', 'Czech Republic'),
( 'DK', 'Denmark'),
( 'DJ', 'Djibouti'),
( 'DM', 'Dominica'),
( 'DO', 'Dominican Republic'),
( 'TP', 'East Timor'),
( 'EC', 'Ecuador'),
( 'EG', 'Egypt'),
( 'SV', 'El Salvador'),
( 'GQ', 'Equatorial Guinea'),
( 'ER', 'Eritrea'),
( 'EE', 'Estonia'),
( 'ET', 'Ethiopia'),
( 'FK', 'Falkland Islands (Malvinas)'),
( 'FO', 'Faroe Islands'),
( 'FJ', 'Fiji'),
( 'FI', 'Finland'),
( 'FR', 'France'),
( 'FX', 'France, Metropolitan'),
( 'GF', 'French Guiana'),
( 'PF', 'French Polynesia'),
( 'TF', 'French Southern Territories'),
( 'GA', 'Gabon'),
( 'GM', 'Gambia'),
( 'GE', 'Georgia'),
( 'DE', 'Germany'),
( 'GH', 'Ghana'),
( 'GI', 'Gibraltar'),
( 'GR', 'Greece'),
( 'GL', 'Greenland'),
( 'GD', 'Grenada'),
( 'GP', 'Guadeloupe'),
( 'GU', 'Guam'),
( 'GT', 'Guatemala'),
( 'GN', 'Guinea'),
( 'GW', 'Guinea-Bissau'),
( 'GY', 'Guyana'),
( 'HT', 'Haiti'),
( 'HM', 'Heard and Mc Donald Islands'),
( 'HN', 'Honduras'),
( 'HK', 'Hong Kong'),
( 'HU', 'Hungary'),
( 'IS', 'Iceland'),
( 'IN', 'India'),
( 'ID', 'Indonesia'),
( 'IR', 'Iran (Islamic Republic of)'),
( 'IQ', 'Iraq'),
( 'IE', 'Ireland'),
( 'IL', 'Israel'),
( 'IT', 'Italy'),
( 'CI', 'Ivory Coast'),
( 'JM', 'Jamaica'),
( 'JP', 'Japan'),
( 'JO', 'Jordan'),
( 'KZ', 'Kazakhstan'),
( 'KE', 'Kenya'),
( 'KI', 'Kiribati'),
( 'KP', 'Korea, Democratic People''s Republic of'),
( 'KR', 'Korea, Republic of'),
( 'XK', 'Kosovo'),
( 'KW', 'Kuwait'),
( 'KG', 'Kyrgyzstan'),
( 'LA', 'Lao People''s Democratic Republic'),
( 'LV', 'Latvia'),
( 'LB', 'Lebanon'),
( 'LS', 'Lesotho'),
( 'LR', 'Liberia'),
( 'LY', 'Libyan Arab Jamahiriya'),
( 'LI', 'Liechtenstein'),
( 'LT', 'Lithuania'),
( 'LU', 'Luxembourg'),
( 'MO', 'Macau'),
( 'MK', 'Macedonia'),
( 'MG', 'Madagascar'),
( 'MW', 'Malawi'),
( 'MY', 'Malaysia'),
( 'MV', 'Maldives'),
( 'ML', 'Mali'),
( 'MT', 'Malta'),
( 'MH', 'Marshall Islands'),
( 'MQ', 'Martinique'),
( 'MR', 'Mauritania'),
( 'MU', 'Mauritius'),
( 'TY', 'Mayotte'),
( 'MX', 'Mexico'),
( 'FM', 'Micronesia, Federated States of'),
( 'MD', 'Moldova, Republic of'),
( 'MC', 'Monaco'),
( 'MN', 'Mongolia'),
( 'ME', 'Montenegro'),
( 'MS', 'Montserrat'),
( 'MA', 'Morocco'),
( 'MZ', 'Mozambique'),
( 'MM', 'Myanmar'),
( 'NA', 'Namibia'),
( 'NR', 'Nauru'),
( 'NP', 'Nepal'),
( 'NL', 'Netherlands'),
( 'AN', 'Netherlands Antilles'),
( 'NC', 'New Caledonia'),
( 'NZ', 'New Zealand'),
( 'NI', 'Nicaragua'),
( 'NE', 'Niger'),
( 'NG', 'Nigeria'),
( 'NU', 'Niue'),
( 'NF', 'Norfork Island'),
( 'MP', 'Northern Mariana Islands'),
( 'NO', 'Norway'),
( 'OM', 'Oman'),
( 'PK', 'Pakistan'),
( 'PW', 'Palau'),
( 'PA', 'Panama'),
( 'PG', 'Papua New Guinea'),
( 'PY', 'Paraguay'),
( 'PE', 'Peru'),
( 'PH', 'Philippines'),
( 'PN', 'Pitcairn'),
( 'PL', 'Poland'),
( 'PT', 'Portugal'),
( 'PR', 'Puerto Rico'),
( 'QA', 'Qatar'),
( 'RE', 'Reunion'),
( 'RO', 'Romania'),
( 'RU', 'Russian Federation'),
( 'RW', 'Rwanda'),
( 'KN', 'Saint Kitts and Nevis'),
( 'LC', 'Saint Lucia'),
( 'VC', 'Saint Vincent and the Grenadines'),
( 'WS', 'Samoa'),
( 'SM', 'San Marino'),
( 'ST', 'Sao Tome and Principe'),
( 'SA', 'Saudi Arabia'),
( 'SN', 'Senegal'),
( 'RS', 'Serbia'),
( 'SC', 'Seychelles'),
( 'SL', 'Sierra Leone'),
( 'SG', 'Singapore'),
( 'SK', 'Slovakia'),
( 'SI', 'Slovenia'),
( 'SB', 'Solomon Islands'),
( 'SO', 'Somalia'),
( 'ZA', 'South Africa'),
( 'GS', 'South Georgia South Sandwich Islands'),
( 'ES', 'Spain'),
( 'LK', 'Sri Lanka'),
( 'SH', 'St. Helena'),
( 'PM', 'St. Pierre and Miquelon'),
( 'SD', 'Sudan'),
( 'SR', 'Suriname'),
( 'SJ', 'Svalbarn and Jan Mayen Islands'),
( 'SZ', 'Swaziland'),
( 'SE', 'Sweden'),
( 'CH', 'Switzerland'),
( 'SY', 'Syrian Arab Republic'),
( 'TW', 'Taiwan'),
( 'TJ', 'Tajikistan'),
( 'TZ', 'Tanzania, United Republic of'),
( 'TH', 'Thailand'),
( 'TG', 'Togo'),
( 'TK', 'Tokelau'),
( 'TO', 'Tonga'),
( 'TT', 'Trinidad and Tobago'),
( 'TN', 'Tunisia'),
( 'TR', 'Turkey'),
( 'TM', 'Turkmenistan'),
( 'TC', 'Turks and Caicos Islands'),
( 'TV', 'Tuvalu'),
( 'UG', 'Uganda'),
( 'UA', 'Ukraine'),
( 'AE', 'United Arab Emirates'),
( 'GB', 'United Kingdom'),
( 'UM', 'United States minor outlying islands'),
( 'UY', 'Uruguay'),
( 'UZ', 'Uzbekistan'),
( 'VU', 'Vanuatu'),
( 'VA', 'Vatican City State'),
( 'VE', 'Venezuela'),
( 'VN', 'Vietnam'),
( 'VG', 'Virgin Islands (British)'),
( 'VI', 'Virgin Islands (U.S.)'),
( 'WF', 'Wallis and Futuna Islands'),
( 'EH', 'Western Sahara'),
( 'YE', 'Yemen'),
( 'YU', 'Yugoslavia'),
( 'YT', 'Mayotte'),
( 'ZR', 'Zaire'),
( 'ZM', 'Zambia'),
( 'ZW', 'Zimbabwe');


-- Valores de la tabla videojuegos --
INSERT INTO videojuegos (id, titulo) VALUES
(1, 'D/Generation HD'),
(2, 'Extreme Exorcism'),
(3, 'Toto Temple Deluxe'),
(4, 'Penarium'),
(5, 'Standpoint'),
(6, 'Kaiju Panic'),
(7, 'Laserlife'),
(8, 'Instant Indie Collection: Vol. 2'),
(9, 'Line of Defense Tactics'),
(10, 'G Prime Into The Rain'),
(11, 'Replay: VHS is not dead'),
(12, 'Ironcast'),
(13, 'MagNets: Fully Charged'),
(14, 'Tetrobot and Co.'),
(15, 'Gryphon Knight Epic'),
(16, 'Cubikolor'),
(17, 'White Knight Chronicles II'),
(20, 'WET'),
(21, 'DiRT 4'),
(22, 'Farpoint'),
(23, 'Golem'),
(24, 'Gran Turismo Sport'),
(25, 'Middle-earth: Shadow of War'),
(26, 'Nex Machina'),
(27, 'Pyre'),
(28, 'Red Dead Redemption 2'),
(29, 'South Park: The Fractured But Whole'),
(30, 'WipEout Omega Collection'),
(31, 'HeartZ: Co-Hope Puzzles'),
(32, 'Destiny 2'),
(33, 'Final Fantasy XII: The Zodiac Age'),
(34, 'Crash Bandicoot N. Sane Trilogy'),
(35, 'The Elder Scrolls Online: Morrowind'),
(36, 'TEKKEN 7'),
(37, 'Star Trek: Bridge Crew'),
(38, 'Injustice 2'),
(39, 'Prey'),
(40, 'GNOG'),
(41, 'Little Nightmares'),
(42, 'What Remains of Edith Finch'),
(43, 'Full Throttle Remastered'),
(44, 'The Disney Afternoon Collection'),
(45, 'Cosmic Star Heroine'),
(46, 'StarBlood Arena'),
(47, 'Yooka-Laylee'),
(48, 'PaRappa The Rapper: Remastered'),
(49, 'Persona 5'),
(50, 'Toukiden 2 with Bonus');
INSERT INTO videojuegos (id, titulo) VALUES
(51, 'APB Reloaded'),
(52, 'Deer Simulator'),
(54, 'Punch Club'),
(55, 'SkyKeepers'),
(56, 'The Inner World'),
(57, 'Shred It!'),
(58, 'WONDER BOY RETURNS'),
(59, 'Anoxemia'),
(60, 'Wolf of the Battlefield: Commando MOBILE'),
(61, 'Fated: The Silent Oath'),
(62, 'Dawn of the Plow'),
(63, 'Has-Been Heroes'),
(64, 'Inferno+'),
(65, 'Heroes of the Monkey Tavern'),
(67, 'Horse Racing 2016'),
(69, 'KINGDOM HEARTS HD 1.5 +2.5 ReMIX'),
(70, 'Korix'),
(71, 'R.B.I. Baseball 14'),
(72, 'MLB The Show 17'),
(73, 'Mushroom Wars'),
(74, 'Perfect Paths'),
(76, 'SXPD: Extreme Pursuit Force. The Comic Book Game Hybrid'),
(77, 'Exploding Kittens - The Official Game'),
(78, 'Old Time Hockey'),
(79, 'Spirit for iPad'),
(80, 'Dungeon Defense: The Invasion of Heroes'),
(82, 'Rain World'),
(84, 'R.B.I. Baseball 17'),
(85, 'Active Soccer 2 DX'),
(86, 'STREET FIGHTER IV VOLT'),
(87, 'Salt and Sanctuary'),
(88, 'Skyforge: Early Adopter Pack'),
(89, 'Geometry Dash'),
(90, 'Wayward Souls'),
(91, 'Skyforge: Extended Early Adopter Pack - Rage of the Berserker'),
(92, 'Bug Heroes'),
(93, '100 Rogues'),
(94, 'Puzzle & Dragons (English)'),
(95, 'Skyforge: Ultimate Early Adopter Pack - Wrath of the Gods'),
(97, 'Dungeon Hunter 4'),
(98, 'Bike Baron'),
(99, 'Snake Pass'),
(100, 'Land Sliders');

-- Ultimo juego introducido a la BBDD inicialmente --
INSERT INTO api_request_state(id,last_game_id) VALUES (1,100);

-- Usuario de prueba --
INSERT INTO usuarios(id, nombre, email, password) VALUES (1, 'TestUser', 'testuser@email.com', '$2a$10$3MpSCThev.3fhbkDhuTwOOUoEBONywL3BpbvgarSyCm/mKDTrWhG6');
